
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Tue Sep 01 16:46:18 CST 2015
//----------------------------------------------------

package minic;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int tipoVariable = 2;
  public static final int ELSE = 5;
  public static final int coma = 31;
  public static final int WHILE = 6;
  public static final int RETURN = 11;
  public static final int corcheteIzquierdo = 12;
  public static final int TRUE = 8;
  public static final int finLinea = 30;
  public static final int IF = 4;
  public static final int operadorMultiplicacion = 25;
  public static final int parentesisIzquierdo = 18;
  public static final int parametroScanf = 32;
  public static final int constStr = 17;
  public static final int nombreVariable = 3;
  public static final int parentesisDerecho = 19;
  public static final int operadorLogico = 28;
  public static final int igual = 20;
  public static final int EOF = 0;
  public static final int llaveDerecha = 15;
  public static final int operadorResta = 24;
  public static final int MAIN = 10;
  public static final int scanf = 22;
  public static final int FALSE = 9;
  public static final int operadorSuma = 23;
  public static final int error = 1;
  public static final int operadorDivision = 26;
  public static final int constChar = 16;
  public static final int entero = 29;
  public static final int FOR = 7;
  public static final int printf = 21;
  public static final int corcheteDerecho = 13;
  public static final int llaveIzquierda = 14;
  public static final int and = 33;
  public static final int operadorRelacional = 27;
}

