
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Sun Sep 06 11:59:05 CST 2015
//----------------------------------------------------

package minic;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int puntoYComa = 33;
  public static final int operadorMultiplicacion = 27;
  public static final int operadorResta = 26;
  public static final int printf = 22;
  public static final int operadorSuma = 25;
  public static final int tipoVariable = 2;
  public static final int coma = 34;
  public static final int igual = 21;
  public static final int parentesisDerecho = 20;
  public static final int FOR = 7;
  public static final int operadorIncrementoDecremento = 29;
  public static final int operadorRelacional = 30;
  public static final int constStr = 18;
  public static final int constChar = 17;
  public static final int llaveIzquierda = 15;
  public static final int MAIN = 10;
  public static final int IF = 4;
  public static final int parentesisIzquierdo = 19;
  public static final int corcheteDerecho = 14;
  public static final int parametroScanf = 35;
  public static final int EOF = 0;
  public static final int nombreVariable = 3;
  public static final int RETURN = 11;
  public static final int TRUE = 8;
  public static final int error = 1;
  public static final int operadorAritmeticoIgual = 24;
  public static final int entero = 32;
  public static final int VOID = 12;
  public static final int corcheteIzquierdo = 13;
  public static final int ELSE = 5;
  public static final int operadorDivision = 28;
  public static final int WHILE = 6;
  public static final int llaveDerecha = 16;
  public static final int and = 36;
  public static final int operadorLogico = 31;
  public static final int FALSE = 9;
  public static final int scanf = 23;
}

