
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Sun Oct 18 20:32:07 CST 2015
//----------------------------------------------------

package minic;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int puntoYComa = 34;
  public static final int operadorMultiplicacion = 29;
  public static final int operadorResta = 28;
  public static final int printf = 24;
  public static final int CHAR = 3;
  public static final int operadorSuma = 27;
  public static final int INTEGER = 2;
  public static final int coma = 35;
  public static final int igual = 23;
  public static final int parentesisDerecho = 22;
  public static final int FOR = 9;
  public static final int operadorIncrementoDecremento = 31;
  public static final int operadorRelacional = 32;
  public static final int constStr = 20;
  public static final int constChar = 19;
  public static final int llaveIzquierda = 17;
  public static final int MAIN = 12;
  public static final int IF = 6;
  public static final int parentesisIzquierdo = 21;
  public static final int corcheteDerecho = 16;
  public static final int parametroScanf = 36;
  public static final int EOF = 0;
  public static final int nombreVariable = 5;
  public static final int RETURN = 13;
  public static final int TRUE = 10;
  public static final int error = 1;
  public static final int operadorAritmeticoIgual = 26;
  public static final int entero = 37;
  public static final int VOID = 14;
  public static final int corcheteIzquierdo = 15;
  public static final int ELSE = 7;
  public static final int operadorDivision = 30;
  public static final int WHILE = 8;
  public static final int llaveDerecha = 18;
  public static final int and = 38;
  public static final int STRING = 4;
  public static final int operadorLogico = 33;
  public static final int FALSE = 11;
  public static final int scanf = 25;
}

